#cloud-config
# IaC4 – VPS-Provisioning
# User: deploy-user | SSH: iac4-deploy-key-20260730

users:
  - name: deploy-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkOYAaYV2j6PDXHAbND5BjkpTEeUZXcYp3zJ5H0gdbw iac4-deploy-key-20260730"

ssh_pwauth: false
disable_root: true
package_update: true

packages:
  - ufw

runcmd:
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw --force enable
  - fallocate -l 4G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab
  - sysctl -w vm.swappiness=1
